lint.select = [
    'F', 'E', 'W', 'C90', 'N', 'D', 'UP', 'ANN', 'ASYNC', 'BLE', 'FBT', 'B',
    'A', 'B', 'C4', 'EM', 'ISC', 'ICN', 'G', 'PIE', 'T20', 'PYI', 'INP', 'Q',
    'RSE', 'RET', 'SLF', 'SIM', 'TID', 'INT', 'ARG', 'PTH', 'TD', 'PD', 'PLE',
    'PLR', 'PLW', 'TRY', 'FLY', 'NPY', 'RUF'
]
lint.ignore = [
    'ANN401',
    'D100',
    'D101',
    'D102',
    'D103',
    'D104',
    'D105',
    'D107',
    'D400',
    'EM101',
    'PLR0913',
    'PLR2004',
    'TD002',
    'TD003',
    'TRY003',
    'TRY301',
    'UP031',
]
line-length=120
target-version="py310"

[lint.flake8-quotes]
inline-quotes = "double"

[lint.flake8-annotations]
mypy-init-return = false
